### ISSUE TITLE
output mapping parallelization

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/output-mapping#15]
Může se
 - poslat importní joby na Storage všechny naráz, Storage je zpracuje jak bude umět, output mapping bude pollovat Storage joby, dokud nebudou všechny hotové
 - paralelizovat upload do S3 napříč všema souborama/tabulkama

Totéž se pak dá udělat v input mappingu

**Comment by padak** [comment]
Epic idea! Kde pro ní mám hlasovat? :)

**Comment by ondrejhlavacek** [comment]
@odinuv brání tomu podle tebe něco?

**Comment by odinuv** [comment]
podpora v storage api clientovi?

**Comment by Halama** [comment]
Tohle je hotový ne?

**Comment by odinuv** [comment]
jo
