### ISSUE TITLE
Metadata write error if new column is introduced  during import

### ISSUE THREAD

**Issue by Halama** [keboola/output-mapping#26]
https://connection.eu-central-1.keboola.com/admin/projects/9/jobs/20776671

![image](https://user-images.githubusercontent.com/903531/50634853-2b506480-0f50-11e9-9c3b-3a796b1cc7fc.png)

Metadata are written before the new column exists in table so it throws error.

How to simulate:
- Configure snowfalke extractor https://help.keboola.com/tutorial/load/database/
- Add table `cars` with only one column selected
- Run the extractor
- Edit configuration and add second column to table
- Run the extractor again -> Internal error

**Comment by Halama** [comment]
Ref: https://github.com/keboola/db-extractor-pgsql/issues/45

**Comment by Halama** [comment]
Workaround is to run the configuration again but it can break some orchestration if new column is introduced

**Comment by Halama** [comment]
Nebo by to ten sloupec mohlo přidat přes api předtím než spustí ty deferred importy.

**Comment by odinuv** [comment]
asi mohlo, ale bude to pekne napikacu - otevrit CSV, vzit tableinfo aktualni tabulky, diffnout, pridat sloupce
- cely je to neatomicky a kdyz do te tabulky zrovna nekdo rypne, tak se to vydrbe na podivnych chybach :/

**Comment by Halama** [comment]
jo ok. tak pokud to tam půjde vyslat až nakonec tak to bude taky v pohodě.

**Comment by ondrejhlavacek** [comment]
mně ten update tabulky předem přijde docela v pohodě, rýpnout do toho může tak jako tak od doby založení jobu po jeho puštění (což může trvat).

ale schovat metadata nakonec je taky oukej, jenom si nejsem jistej, jestli je jak je nějak jednoduše předat?

**Comment by Halama** [comment]
udelal bych to tak jak to bylo doted, tzn. deffered zapis metadat. Webalize ted quickfixuji komponenty. Ale spravne by se to melo myslim vyresit tak ze se to do sapi sapi nebude uplatnovat webalize sloupcu.

**Comment by odinuv** [comment]
Kdyz komponenta zapisuje sloupec `Account: Account Number` tak to doted fungovalo jen proto, ze k nemu neposila metadata. Tento update to rozbil i kdyz metadata neposila. A defered metadata to vrati do stavu, ze to bude fungovat jen pokud tam ty metadata nebudou. Pokud by je tam ta komponenta poslala, tak to zase vyfailuje. 

Cili to uz by bylo jednodussi tam ten sloupec pridavat jen pokud jsou pro nej zadany metadata

**Comment by odinuv** [comment]
reverted https://github.com/keboola/docker-bundle/commit/340c6a277595281c7a8466fbf9dfd39abcc2a9bc

**Comment by odinuv** [comment]
vzhledem k tomu, ze tu variantu s pridanim sloupce pred jsme ani na tri pokusy netrefil spravne - https://github.com/keboola/output-mapping/pull/31, tak jsem udelal i tu variantu s tim, ze se metadata zapisou az po loadu https://github.com/keboola/output-mapping/pull/32

**Comment by Halama** [comment]
Pokud se bude nasazovat varianta s přídáváním sloupce tak radši až po fixu https://github.com/keboola/connection/issues/1762

**Comment by Halama** [comment]
validace jména sloupce mergnuta a bude nasazena jakmile bude zelený https://travis-ci.com/keboola/connection/builds/98008328

**Comment by Halama** [comment]
ok, nevěděl jsem na jakém řešení se to ustálilo

**Comment by odinuv** [comment]
no zatim na zadnym. to pridavani sloupce je fixnuty v masteru, a ten zapis metadat po loadu je ready na mergnuti. No a ja bych radsi rovnou nasadil ten zapis po loadu, jestli nemas neco proti nebo najlos nebo nekdo jinej :)

**Comment by odinuv** [comment]
update nasazenej, zaviram a doufam, ze je uz to nebudu znovu otevirat
