### ISSUE TITLE
Writer::uploadTable() refactoring?

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/output-mapping#29]
Koukám na podmínku

```
if ($this->client->tableExists($config["destination"])) {
    // import into existing table code
} else {
   // table create and import code
}
```
Nehodilo by se to přepsat na cca tohle? Přijde mi to takový logičtější.
```
if (!$this->client->tableExists($config["destination"])) {
     // table create code
}
// import into existing table code
```

**Comment by ondrejhlavacek** [comment]
Co myslíš @odinuv?

**Comment by odinuv** [comment]
no pred 14 dnama jsi me to rozmluvil, ze to jeste refactorovat nebudem a jeste to chvilku nechame hnit :)

**Comment by ondrejhlavacek** [comment]
Jojo, taky proto jsme jen založil issue typu question :-)

**Comment by odinuv** [comment]
no jeste bych to teda nechal chvilku hnit :) ale issue tu nechame
