### ISSUE TITLE
Table import columns and withoutHeaders 

### ISSUE THREAD

**Issue by Halama** [keboola/output-mapping#7]
`withoutHeaders` should not be set together with `columns` because it overrides `columns` parameter.

https://github.com/keboola/output-mapping/blob/42d13349b3ca4b7da02d10fbf1be75ac0011533e/Writer/Writer.php#L589

https://github.com/keboola/connection/issues/1210

## How to simulate the issue

- Configure Snowflake extractor with one table
- Run the extractor
- Change table column names in source snowflake db
- Run extractor again - it writes the table with old columns and then throws internal errors on metadata write where it properly uses new columns names.

## Expected behaviour
- It throws user error on table import because of columns mismatch

**Comment by Halama** [comment]
It happed also on new configuration
https://keboola.slack.com/archives/C09U3R1J4/p1519126247000375
So it was a SNFLK bug https://snowflakecommunity.force.com/s/case/5000Z00000tENHZQA4/query-result-inconsistency and we fixed it in snowflake extractor https://github.com/keboola/db-extractor-snowflake/commit/b8c96250016358dfc4edc4b5f211b410c8795cd8 
But I think the issue will still be present, I'll try it when the extractor will be deployed.

**Comment by Halama** [comment]
Extractor is fixed and issue is still here https://connection.keboola.com/admin/projects/4088/jobs/358282958?q=

**Comment by odinuv** [comment]
fixed in 53f561907aeddd42c153400d46257f4032f6f27e

**Comment by Halama** [comment]
@odinuv bohuzel to vypada ze to tam je jeste na jednom miste https://github.com/keboola/output-mapping/blob/53f561907aeddd42c153400d46257f4032f6f27e/Writer/Writer.php#L617

**Comment by Halama** [comment]
V tomhle pripade to asi nic nerozbiji ale chtel bych pak v SAPI udelat upravu aby to hodilo chybu kdyz zadas oboje https://github.com/keboola/connection/issues/1210#issuecomment-367256608

**Comment by odinuv** [comment]
hm, asi na to timpadem ale nepujde udelat test, proste bych to teda vyhodil, a kdyby to tam nekdo nekdy vratil, tak se to v budoucnu zachyti na backendu

**Comment by Halama** [comment]
jo ok

**Comment by odinuv** [comment]
fixed in 29252f9
